export const loremIpsum =
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer mollis congue velit, nec consectetur quam pellentesque at. Aenean finibus mauris dolor, porta ornare justo lobortis vitae. Quisque lacinia nulla arcu. Nunc consequat urna et risus consequat, in sodales metus vulputate. Nulla non leo eget nibh consectetur egestas sed sit amet magna. Duis vel dui venenatis, molestie ex et, bibendum eros. Mauris libero nisi, porttitor quis tempus blandit, sagittis id magna. Nam eu posuere velit, ac fermentum orci. Praesent dignissim urna vitae neque suscipit, in scelerisque enim porta. Mauris sit amet placerat leo, at lacinia elit. Nulla facilisi. Sed dictum suscipit ornare. In eu mattis lacus.

  Etiam velit elit, fringilla bibendum est nec, iaculis rutrum est. Praesent scelerisque tincidunt dui, eget tempus lorem sollicitudin efficitur. Integer tincidunt dictum ultricies. In porta nibh ut mauris pellentesque imperdiet. Nam ut pharetra odio, sollicitudin sollicitudin turpis. Nulla rutrum malesuada mauris in congue. Vestibulum efficitur, odio a sagittis vehicula, est velit fringilla tellus, vel volutpat tortor odio non nunc. Curabitur at vestibulum tortor, nec commodo ligula. Phasellus nibh lacus, tempor vitae aliquam in, tempor mattis ipsum.

  Vestibulum et justo ac eros vulputate vehicula. Nam sit amet scelerisque ligula, eget sagittis turpis. Suspendisse egestas urna vel ultrices sollicitudin. Nulla et dui tempor, hendrerit urna sit amet, lobortis lacus. Ut vehicula ullamcorper blandit. Cras diam leo, venenatis eu nunc vel, ullamcorper facilisis sapien. Duis nec aliquet mi, et vehicula sapien. Mauris ex lacus, vulputate nec lorem ut, commodo scelerisque mi. Nulla semper ligula sit amet magna aliquam pellentesque. In vel vehicula nisl. Ut elit arcu, sagittis at nunc ut, maximus molestie ex.

  Suspendisse et tincidunt tellus, vitae fringilla magna. Maecenas tincidunt porta leo sed dignissim. Vivamus pharetra, mi non rutrum tincidunt, tellus felis tincidunt urna, quis facilisis tortor nulla ut dolor. Sed cursus maximus tempus. Nullam sem eros, vestibulum vel velit eget, molestie venenatis sapien. Suspendisse tempor ante lorem, et ultrices ipsum rhoncus vitae. Suspendisse potenti. Aenean ullamcorper finibus risus, non accumsan sapien scelerisque ut. Phasellus lacinia tellus dui, a dapibus sapien pharetra vitae. Nam bibendum euismod orci, nec molestie urna mattis ac.`;

export const conditions = ['Asthma', 'Diabetes', 'Heart Disease', 'High Blood Pressure', 'Kidney Disease', 'Seizures', 'Stroke'];
